# Test against multiple versions of Node.js
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "0.11"
  - "0.10"

services:
  - xvfb
  - postgresql

# Configure postgres user
before_script:
  - psql -c "CREATE USER lds WITH PASSWORD 'chickenfoot';" -U postgres

# Allow Firefox to operate in framebuffer
before_install:
  - "export DISPLAY=:99.0"
