common: &common
  adapter: postgresql
  username: lds
  password: chickenfoot

development:
  <<: *common
  database: lds_dev

test: &test
  <<: *common
  database: lds_test

production:
  <<: *common
  database: production

cucumber:
  <<: *test
