common: &common
  adapter: postgresql
  username: lds
  password: chickenfoot

development:
  <<: *common
  database: dev

test: &test
  <<: *common
  database: test

production:
  <<: *common
  database: production

cucumber:
  <<: *test